# Generated by Django 3.2 on 2021-12-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemGroups', '0003_auto_20211214_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('units', models.CharField(max_length=100, null=True)),
                ('attributes', models.TextField(null=True)),
                ('tax', models.CharField(default='VAT', max_length=100, null=True)),
            ],
        ),
    ]
