# Generated by Django 3.2 on 2021-12-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_alter_items_item_group'),
        ('orders', '0005_alter_orders_item_group'),
        ('ItemGroups', '0004_itemgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemGroups',
        ),
    ]
