# Generated by Django 3.2 on 2021-12-14 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0002_auto_20211214_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('sku', models.IntegerField(null=True)),
                ('unit_of_measure', models.CharField(default='unit_type', max_length=100)),
                ('purchase_price', models.CharField(max_length=100, null=True)),
                ('cost_price', models.CharField(max_length=100, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='suppliers.supplier')),
            ],
        ),
    ]
