# Generated by Django 3.2 on 2021-12-14 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItemGroups', '0003_auto_20211214_1922'),
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='item_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemGroups.itemgroups'),
        ),
        migrations.AddField(
            model_name='items',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
