# Generated by Django 3.2 on 2021-12-14 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='deliver_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='deliver_to',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='item_attribute',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orders',
            name='item_group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='item_quantity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_terms',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
