# Generated by Django 3.2 on 2021-12-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20211214_1821'),
        ('orders', '0003_alter_orders_item_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='supplier_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='suppliers.supplier'),
        ),
    ]
