# Generated by Django 3.2 on 2021-12-14 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItemGroups', '0004_itemgroup'),
        ('orders', '0004_alter_orders_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ItemGroups.itemgroup'),
        ),
    ]
